language: node_js
node_js:
    - 12.18.1
before_script:
    - yarn build:nowatch
before_install:
    - openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv
      -in .env.enc -out .env -d
